### ISSUE TITLE
Using existing mysql instance for Flowable

### ISSUE THREAD

**Issue by jy006** [flowable/helm#12]
I was trying to not have Flowable install a separate instance of postgres essentially dedicated only for the purposes of an instance of Flowable. So, for simplicity sake, I'm trying to move my Flowable database to an existing mysql.

My flowable instance is open source flowable version 6.7.2.

I saw these lines in `ui.yaml` helm chart:
```
{{- if and .Values.database.datasourceDriverClassName .Values.database.datasourceUrl }}
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: {{ .Values.database.datasourceDriverClassName | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.database.datasourceUrl | quote }}
```
So I added these lines in `values.yaml`, but it didn't work.
```
database:
  datasourceDriverClassName: com.mysql.jdbc.Driver
```
I have also tried `com.mysql.cj.jdbc.Driver` with no luck.

The error message I got was `Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver`. What should I put as datasource driver if I wanted to use mysql? Or is there no mysql driver included in current version of flowable? If so, will it be included in future versions?

Thank you

**Comment by yvoswillens** [comment]
Hi @jy006 

The MySQL jdbc driver is indeed not included in the default image.
So if you want to use that you need to get it in the classpath. This could be done by creating your own image extending the default Flowable one (and adding the jdbc jar file), mounting it with a volume, or load it via a sidepod.

Regards,

Yvo
