### ISSUE TITLE
Helm Chart Repo index.yaml is incorrect

### ISSUE THREAD

**Issue by Toady00** [flowable/helm#3]
I'm trying to install the 6.7.2 helm chart and the repo provided in the instructions doesn't provide the correct urls in the index.yaml file. If you look at https://flowable.github.io/helm/index.yaml The snapshot 3 and 4 urls are correct as they point to the github releases but all of the previous helm charts that use the flowable.github.io domain provide 404's. Just running

```
wget https://flowable.github.io/helm/flowable-6.7.2.tgz
```

Returns a 404. What is the correct url for the 6.7.2 helm chart and can we get the index.yaml file fixed so helm tools work properly?

**Comment by yvoswillens** [comment]
Seems to be something wrong with the static file hosting of the GitHub pages.
Will investigate.

**Comment by yvoswillens** [comment]
Fixed broken links.
